### ISSUE TITLE
I am seeing a lot of problems

### ISSUE THREAD

**Issue by mcorbridge** [kaftz/hand-ranker#1]
I am using your file as a base for a typescript file.  That shouldn't be a problem.  All js is valid ts, albeit with a tiny bit of massaging.  However some of your functions don't make any sense.  For example:

var isXOfKind = false;

followed by:

while (isXOfKind.length < 5) {
            var nextCard = this.highCard(cards, function (c) { return !added[c.v]; });
            isXOfKind.unshift(nextCard);
            added[nextCard.v] = true;
        }

What?  How can a boolean have a length?

There are others ....

**Comment by kaftz** [comment]
I'm not exactly familiar with typescript, but I can explain the function in question.

In that scope isXOfKind is either a boolean (false) or a reference to an array of cards. Before that while block is executed, isXOfKind will always be assigned a filtered array. This pattern is probably repeated throughout.

I hope that helps!
