### ISSUE TITLE
function isStraight KO when the array contains the same values

### ISSUE THREAD

**Issue by SilverSprings** [kaftz/hand-ranker#2]
This hand doesn't give me a straight but 2 pairs. I think there is an issue in the function isStraigth : 
[{s:'s',v:11},
{s:'d',v:2},
{s:'c',v:7},
{s:'d',v:7},
{s:'h',v:12},
{s:'c',v:13},
{s:'s',v:5},
{s:'h',v:3},
{s:'d',v:3},
{s:'s',v:2},
{s:'s',v:1},
{s:'c',v:8},
{s:'c',v:4}];

**Comment by SilverSprings** [comment]
pullRequest : update of isStraight function

**Comment by kaftz** [comment]
Thanks for catching this.
